const data = [
	{
		name: "Government Sector",
		type: [
			{
				name: "Educational Institutions",
				subtype: [
					"Government Primary School (GPS) (Kindergarten to Grade 5)",
					"Government Higher Primary School (GHPS) (Grade 6 to Grade 8)",
					"Government High School (GHS) (Grade 1 to Grade 10)",
					"Government Senior Secondary School (GSS) (Grade 11 and Grade 12)",
					"Government College (Undergraduate Programs)",
					"Government Universities (Undergraduate and Postgraduate Programs)",
					"Others",
				],	
			},
			{
				name: "Public Health Services",
				subtype: [
					"Public Hospitals: These provide a wide range of healthcare services, from emergency care to specialized treatments.",
					"Community Health Centers: Focus on primary care and preventive services in local communities.",
					"Government Clinics: Offer basic healthcare services, often focusing on primary care.",
					"Public Health Departments: Responsible for health policy, regulation, and population health programs.",
					"Mental Health Facilities: Provide treatment for mental health issues and support services.",
					"Research Institutes: Involved in medical research, often in collaboration with hospitals or universities.",
					"Specialized Government Healthcare Programs: For specific groups, like veterans or low-income populations.",
					"Others",
				],
			},
			{
				name: "Public Safety and Law Enforcement",
				subtype: [
					"Police Departments: Responsible for maintaining public order, preventing and investigating crimes.",
					"Fire Departments: Focused on firefighting, emergency medical services, and rescuing operations.",
					"Emergency Medical Services (EMS): Provide urgent medical care and ambulance services.",
					"Border Security Forces: Protect and monitor national borders.",
					"Coast Guard: Responsible for maritime safety, security, and environmental protection.",
					"Disaster Response Agencies: Handle responses to natural disasters and emergencies.",
					"Correctional Facilities: Manage prisons and rehabilitate offenders.",
					"Traffic and Highway Patrols: Enforce traffic laws and ensure road safety.",
					"Others",
				],
			},
			{
				name: "Public Utilties",
				subtype: [
					"Water Supply Services: Managing and supplying water for domestic and industrial use.",
					"Electricity Providers: Generating and distributing electrical power.",
					"Natural Gas Services: Supplying gas for heating, cooking, and energy.",
					"Waste Management Services: Handling garbage collection, recycling, and disposal.",
					"Public Transit Systems: Operating buses, trains, subways for public transportation.",
					"Sewage Treatment: Managing and treating wastewater.",
					"Telecommunication Services: In some regions, providing phone and internet services.",
					"Others",
				],
			},
			{
				name: "Cultural Institutions",
				subtype: [
					"Public Museums: Display historical, scientific, artistic, or cultural artifacts.",
					"National and Public Libraries: Provide access to books, digital media, and other resources.",
					"Historical Sites and Monuments: Preserve and exhibit places of historical significance.",
					"Public Art Galleries: Showcase art collections for education and enjoyment.",
					"Cultural Centers: Offer venues for cultural events and community activities.",
					"Public Theaters and Performing Arts Venues: Host performances like plays, concerts, and dances.",
					"Archives: Preserve historical documents and records.",
					"Others",
				],
			},
			{
				name: "Social Welfare Services",
				subtype: [
					"Child and Family Services: Offering support and protection for children and families in need.",
					"Unemployment Benefits and Job Training Programs: Providing financial assistance and training to the unemployed.",
					"Public Housing: Offering affordable housing options.",
					"Social Security Administration: Managing retirement, disability, and survivorship benefits.",
					"Health and Human Services: Overseeing various health and welfare programs.",
					"Elderly Care Services: Providing support and care for senior citizens.",
					"Disability Services: Offering assistance to individuals with disabilities.",
					"Defense and Military: National armed forces and related departments",
					"Others",
				],
			},
			{
				name: "International Organizations",
				subtype: [
					"United Nations (UN): An international organization focused on maintaining international peace and security, developing friendly relations among nations, and promoting social progress, better living standards, and human rights.",
					"World Bank: Provides financial and technical assistance to developing countries for development programs that are expected to improve economic prospects and quality of life.",
					"International Monetary Fund (IMF): Works to stabilize the international monetary system and acts as a forum for cooperation on international monetary problems.",
					"World Health Organization (WHO): Specialized agency of the United Nations responsible for international public health.",
					"International Labour Organization (ILO): Deals with labor problems, particularly international labor standards and decent work for all.",
					"UNESCO (United Nations Educational, Scientific and Cultural Organization): Encourages international peace and universal respect by promoting collaboration among nations through education, science, and culture.",
					"World Trade Organization (WTO): Deals with the global rules of trade between nations.",
					"Others",
				],
			}
		],
	},
	{
		name: "Private Sector",
		type: [
			{
				name: "Private Educational Institutions",
				subtype: [
					"Secondary School (Grade 1 to 10)",
					"Senior Secondary School/College (Grade 11 & 12)",
					"K-12 School",
					"Undergraduate College",
					"Postgraduate College",
					"Others",
				],
			},
			{
				name: "For-Profit Corporations",
				subtype: [
					"Manufacturing (Specify subtype, e.g., Electronics, Consumer Goods)",
					"Renewable Energy",
					"Retail & E-commerce",
					"Metals and Mining",
					"Oil and Gas",
					"Healthcare Services",
					"Medical Devices",
					"Banking and Finance",
					"Telecommunications",
					"Media and Entertainment",
					"Transportation and Logistics",
					"Real Estate",
					"IT and Business Process Management (BPM)",
					"Food and Beverage",
					"Pharmaceuticals",
					"Automotive",
					"Tourism and Hospitality",
					"Insurance",
					"Management Consulting",
					"Environmental Consulting",
					"Aviation",
					"Fintech and Financial Services",
					"Biotechnology",
					"Chemicals",
					"Construction",
					"Defense Manufacturing",
					"Aerospace and Defense",
					"Sports Management and Recreational Services",
					"Textiles and Apparel",
					"Education and EdTech",
					"Agriculture and Agribusiness",
					"Environmental Services and Sustainability",
					"Digital Marketing and Advertising",
					"Professional Services (Legal, Accounting)",
					"Arts and Culture (Museums, Galleries)",
					"Consumer Electronics",
					"Publishing and Printing",
					"Maritime (Shipping and Port Operations)",
					"Utilities (Electric, Water, and Waste Management)",
					"Software Development",
					"Cybersecurity",
					"Others",
				],
			},
			{
				name: "Non Profit Orgnaizations",
				subtype: [
					"SDG 1 - No Poverty",
					"SDG 2 - Zero Hunger",
					"SDG 3 - Good Health and Well-being",
					"SDG 4 - Quality Education",
					"SDG 5 - Gender Equality",
					"SDG 6 - Clean Water and Sanitation",
					"SDG 7 - Affordable and Clean Energy",
					"SDG 8 - Decent Work and Economic Growth",
					"SDG 9 - Industry, Innovation, and Infrastructure",
					"SDG 10 - Reduced Inequalities",
					"SDG 11 - Sustainable Cities and Communities",
					"SDG 12 - Responsible Consumption and Production",
					"SDG 13 - Climate Action",
					"SDG 14 - Life Below Water",
					"SDG 15 - Life On Land",
					"SDG 16 - Peace, Justice, and Strong Institutions",
					"SDG 17 - Partnerships for the Goals",
					"Others",
				],
			}
		],
	},
	{
		name: "Educational & Entertainment Venue",
		type: [{
			name: "Educational & Entertainment Venues",
			subtype: [
				"Public Museums: Display historical, scientific, artistic, or cultural artifacts.",
				"Science Centers: Interactive venues for science learning.",
				"Historical Sites and Monuments: Preserve and exhibit places of historical significance",
				"Theme Parks and Amusement Parks: Providing recreational activities and themed experiences.",
				"Public Art Galleries: Showcase art collections for education and enjoyment.",
				"Theaters: For performing arts like plays, musicals, and concerts.",
				"Cinemas: Screening films and documentaries.",
				"Libraries and Archives: Provide access to historical documents, books, digital media, and other resources.",
				"Aquariums and Zoos: Displaying aquatic and terrestrial wildlife.",
				"Cultural Centers: Offer venues for cultural events and community activities.",
				"Others",
			],
		}]
	}
]

export default data;